Add conversions to/from networkx graphs
mosdef-hub/gmso pull request #472
Opened 2020-10-09 18:36 UTC by uppittu11

In this PR I added a very simple conversion to and from networkx graphs. At the moment, only site and bond data is transferred when converting. Angles, dihedrals, impropers, subtops, metadata (mixing rules), etc. are ignored making it a lossy conversion to networkx. Let me know how this could be improved.

2020-10-18 16:20 UTC, rsdefever commented
What is the use case for `from_networkx`? I can see the value of  `to_networkx` graph from the topology (as a more abstract representation of the connectivity), but why support the inverse?

2020-10-18 17:22 UTC, justinGilmer commented
Personally, the `from_networkx` functionality provides another way to create topologies, from a much more abstract representation of a molecule. Especially if you wanted to iterate through various bonded variations it can sometimes be easier to use a graph-based algorithm.

Although similar things could be done with smiles strings, I want to note.

We can also export a lot of compounds and such as bond graphs, which are a bit more general and can be visualized using a plethora of graph visualization libraries like graphviz. Being able to store these as graph objects and then convert back to a topology can be beneficial.

2020-10-18 17:49 UTC, rsdefever commented
> Personally, the `from_networkx` functionality provides another way to create topologies, from a much more abstract representation of a molecule. Especially if you wanted to iterate through various bonded variations it can sometimes be easier to use a graph-based algorithm.

That is a great point, thanks for helping me understand.

2020-10-20 22:36 UTC, justinGilmer requested changes
Some small suggestions and a few edge cases (pun _not_ intended)

2020-10-20 22:36 UTC, justinGilmer commented on gmso/external/convert_networkx.py
> +
I think we should have a validation check here to either ensure it is a `networkx` graph object, or try to coerce into a `networkx` graph

2020-10-20 22:36 UTC, justinGilmer commented on gmso/external/convert_networkx.py
> +    for b in top.bonds:
What about the case where a top has no bonds, they would just be edgeless nodes. Would that work?
I dont think a node would be created based on the logic.

Also, if there were two ethanes in the system, would the `Graph` contain two separate graphs within it, or two sets of connected nodes?

2020-10-20 22:36 UTC, justinGilmer commented on gmso/tests/test_convert_networkx.py
> +        assert ethane.n_sites == ethane_to_nx.number_of_nodes()
these are great tests, if we can add in the possibilities above, this is good to go afterwards

2020-11-05 21:46 UTC, RainierBarrett commented
One slightly hacky way to preserve some more information than just the molecular structure would be to make an unconnected sub-graph with one node, and just make a rule for how that node's weight will hold the metadata etc. that is currently being lost... Any thoughts?

2020-12-07 22:35 UTC, justinGilmer requested changes
Looks like the unit tests handle pretty much every case I am concerned with, my only change would be in the from_networkx method. I think we still need a check to ensure that the graph object is a nx graph. Although that could be abstracted out to a separate method like: _valdidate_graph. Although I am not sure that is necessary. Other than that, this is good to merge for me.

2020-12-08 17:48 UTC, umesh-timalsina commented on gmso/external/convert_networkx.py
> +            raise GMSOError("Nodes must be gmso.core.Site objects")
```suggestion
            raise GMSOError("Nodes must be gmso.core.Site objects")
            raise GMSOError("Nodes must be instances of gmso.abc.Site")
```

2020-12-08 18:06 UTC, umesh-timalsina approved these changes

2020-12-08 18:06 UTC, justinGilmer approved these changes

2020-12-08 19:20 UTC, merged

2020-12-10 23:04 UTC, CalCraven commented
If you import gmso.external, then you can only see openmm, mbuild, and parmed converters. You have to manually import gmso.external.convert_networkx to get this functionality. Probably worth it to make that converter automatically import when importing gmso.external. 

Also, but just a side note: you have to separately import gmso.external already. Not sure if that is intended or something we want to have available during the initial gmso import.

2020-12-10 23:38 UTC, umesh-timalsina commented
```python
(gmso-dev) umesh@isisdell:~$ python
Python 3.6.10 | packaged by conda-forge | (default, Apr 24 2020, 16:44:11) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from gmso.external import convert_networkx
>>> 

```
I am able to import it like the snippet above. @CalCraven, could you point a code snippet to reproduce the issue you mentioned.