Fix bug when converting mbuild
mosdef-hub/gmso pull request #571
Opened 2021-07-13 20:42 UTC by daico007

Fix bug related to #566 and #570. Rename one of the ethane fixture and fix mbuild position conversion issue.

2021-07-13 20:46 UTC, justinGilmer requested changes
Extra print statements, but looks good. That was the fix I was thinking for that section. 

Real quick, do we need to make any edits to the others tests for those that might have been using `ethane_from_scratch`

2021-07-13 20:46 UTC, justinGilmer commented on gmso/tests/test_convert_mbuild.py
> +            print(new[i].xyz)
Extraneous print statements.

2021-07-13 20:55 UTC, daico007 commented
The only thing is I don't which test that actually need to use that `ethane_from_scratch`, my guess would be something in `test_topology.py` (I can sit down and go through it sometime later today).

2021-07-14 19:02 UTC, justinGilmer approved these changes

2021-07-15 19:58 UTC, merged