fix typo when converting foyer XML
mosdef-hub/gmso pull request #636
Opened 2022-02-11 19:19 UTC by daico007

The naming mismatch (`combining_rule` vs `combiningRule`) causing issues converting combining rule information from foyer XML to gmso XML. This PR fix this by sticking to `combiningRule`.

2022-02-11 19:26 UTC, daico007 commented
This should fix the second portion of #617

2022-02-21 22:29 UTC, justinGilmer requested changes
Can you add a test to ensure that the combining rule is being found properly now?

After that, it should be g2g

2022-02-22 15:32 UTC, daico007 commented
unit test added

2022-02-22 20:06 UTC, justinGilmer approved these changes

2022-02-28 16:08 UTC, merged