Add position restraints for Site
mosdef-hub/gmso pull request #770
Opened 2023-10-07 19:26 UTC by daico007

Add `position_restraints` for site and write it out in GROMACS top writer. Pending unit test.

2023-11-13 16:36 UTC, CalCraven commented
I think the tests should go in `test_atom.py` and `test_top.py`. One that you can add a restraint to a site and parse it, and one that a topology with restraints will properly be id'd in gromacs. I think the best way to do that would be to make a `restrained_water_topology` in `base_test.py` for other engines to use, and then call that.

2023-11-14 01:35 UTC, daico007 commented
This PR includes the fix for the current failing CI tests.

2023-11-14 02:04 UTC, daico007 commented
All unit tests has been added.

2023-11-28 15:55 UTC, CalCraven requested changes
Just remove the duplicate files and it should be good to go!

2023-11-28 15:55 UTC, CalCraven commented on gmso/utils/files/spce.xml
> +<ForceField version="0.0.1" name="SPC/E Water" combining_rule="geometric">
I think this file already exists in the `utils/files/gmso_xmls/test_ff_styles` directory. I think you can probably delete it and source from there.

2023-11-28 15:55 UTC, CalCraven commented on gmso/tests/base_test.py
> +        spce_ff = ForceField(get_fn("spce.xml"))
```suggestion
        spce_ff = ForceField(get_fn("gmso_xmls/test_ffstyles/spce.xml"))
```

2023-11-28 16:08 UTC, daico007 commented on gmso/tests/base_test.py
> +        spce_ff = ForceField(get_fn("spce.xml"))
Good catch! Done.

2023-11-28 16:14 UTC, CalCraven approved these changes
Once tests pass, lets merge it.

2023-11-28 19:15 UTC, merged